[package]
name = "realtime-rays"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
glm = "0.2.3"
sdl2 = "0.35.2"
